package org.abstractmeta.code.g.core.code;

import org.abstractmeta.code.g.code.JavaField;

import java.lang.annotation.Annotation;
import java.lang.reflect.Type;
import java.util.List;


/**
 * Provides implementation of interface org.abstractmeta.toolbox.code.JavaField
 * This class has been auto generated by g-toolbox.
 */
public class JavaFieldImpl implements JavaField {


    private final Type type;

    private final String initBody;

    private final List<String> modifiers;

    private final String name;

    private final List<Annotation> annotations;

    private final List<String> documentation;
    
    private final boolean immutable;

    public JavaFieldImpl(Type type, String initBody, List<String> modifiers, String name, List<Annotation> annotations, List<String> documentation, boolean immutable) {
        this.type = type;
        this.initBody = initBody;
        this.modifiers = modifiers;
        this.name = name;
        this.annotations = annotations;
        this.documentation = documentation;
        this.immutable = immutable;
    }

    public Type getType() {
        return this.type;
    }

    @Override
    public boolean isImmutable() {
        return immutable;
    }

    public String getInitBody() {
        return this.initBody;
    }

    public List<String> getModifiers() {
        return this.modifiers;
    }

    public String getName() {
        return this.name;
    }

    public List<Annotation> getAnnotations() {
        return this.annotations;
    }

    public List<String> getDocumentation() {
        return this.documentation;
    }

}