package org.abstractmeta.code.g.examples.model4.builder;

import org.abstractmeta.code.g.examples.model4.Employee;
import org.abstractmeta.code.g.examples.model4.impl.EmployeeImpl;
/**
 * This source code was automatically generated by code-g plugin.
 */

public class EmployeeBuilder {
    private String name;
    private transient boolean namePresent;
    private int id;
    private transient boolean idPresent;
    private String group;
    private transient boolean groupPresent;


    public EmployeeBuilder setName(String name) {
        this.name = name;
        this.namePresent = true;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public EmployeeBuilder setNamePresent(boolean namePresent) {
        this.namePresent = namePresent;
        return this;
    }

    public boolean isNamePresent() {
        return this.namePresent;
    }

    public EmployeeBuilder setId(int id) {
        this.id = id;
        this.idPresent = true;
        return this;
    }

    public int getId() {
        return this.id;
    }

    public EmployeeBuilder setIdPresent(boolean idPresent) {
        this.idPresent = idPresent;
        return this;
    }

    public boolean isIdPresent() {
        return this.idPresent;
    }

    public EmployeeBuilder setGroup(String group) {
        this.group = group;
        this.groupPresent = true;
        return this;
    }

    public String getGroup() {
        return this.group;
    }

    public EmployeeBuilder setGroupPresent(boolean groupPresent) {
        this.groupPresent = groupPresent;
        return this;
    }

    public boolean isGroupPresent() {
        return this.groupPresent;
    }

    public Employee build() {
        Employee result = new EmployeeImpl(name, id, group);
        return result;
    }

    public EmployeeBuilder merge(Employee instance) {
        if(instance.getName() != null) {
            this.setName(instance.getName());
        }
        this.setId(instance.getId());
        if(instance.getGroup() != null) {
            this.setGroup(instance.getGroup());
        }
        return this;
    }

}