package org.abstractmeta.code.g.examples.model4.builder;

import org.abstractmeta.code.g.examples.model4.Employee;
import org.abstractmeta.code.g.examples.model4.impl.EmployeeImpl;
/**
 * This source code was automatically generated by code-g plugin.
 */

public class EmployeeBuilder {
    private String name;
    private boolean _namePresent;
    private int id;
    private boolean _idPresent;
    private String group;
    private boolean _groupPresent;


    public EmployeeBuilder setName(String name) {
        this.name = name;
        this._namePresent = true;
        return this;
    }

    public String getName() {
        return this.name;
    }

    public boolean isNamePresent() {
        return this._namePresent;
    }

    public EmployeeBuilder setId(int id) {
        this.id = id;
        this._idPresent = true;
        return this;
    }

    public int getId() {
        return this.id;
    }

    public boolean isIdPresent() {
        return this._idPresent;
    }

    public EmployeeBuilder setGroup(String group) {
        this.group = group;
        this._groupPresent = true;
        return this;
    }

    public String getGroup() {
        return this.group;
    }

    public boolean isGroupPresent() {
        return this._groupPresent;
    }

    public Employee build() {
        Employee result = new EmployeeImpl(name, id, group);
        return result;
    }

    public EmployeeBuilder merge(Employee instance) {
        if(instance.getName() != null) {
            this.setName(getName());
        }
        this.setId(instance.getId());
        if(instance.getGroup() != null) {
            this.setGroup(getGroup());
        }
        return this;
    }

}