package org.abstractmeta.code.g.examples.model4.impl;

import org.abstractmeta.code.g.examples.model4.Employee;
/**
 * This source code was automatically generated by code-g plugin.
 */

public class EmployeeImpl implements Employee {
    private final String name;
    private final int id;
    private final String group;

    public EmployeeImpl(String name, int id, String group) {
        this.name = name;
        this.id = id;
        this.group = group;
    }

    public String getName() {
        return this.name;
    }

    public int getId() {
        return this.id;
    }

    public String getGroup() {
        return this.group;
    }

}